version: 0.1

phases:
  build:
    commands:
      - echo nothing to build here
artifacts:
  files:
    - index.html
    - babel.html
    - react.html
    - favicon.ico
    - styles/main.css
    - images/*
    - js/*
