---
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
phases:
  build:
    commands:
      - "npm run webpack"
  pre_build:
    commands:
      - "npm install"
      - "npm test"
version: 0.1
