version: 0.1

phases:
  build:
    commands:
      # install dependencies
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - babel.html
    - react.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
